### ISSUE TITLE
reservoir not detected when not fully contained in 

### ISSUE THREAD

**Issue by aweerts** [Deltares/hydromt_wflow#262]
### HydroMT-Wflow version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT-Wflow.

### Reproducible Example

Reservoirs ignored even if >99% is in subbasin. This happens for 100+ basins when deriving 3200 models
hack/solution 2022 (Dirk): waarschijnlijk is het voor deze case op te lossen door predicate="contains" weg te laten.
Suggestion to add this as an option in hydromt-wflow 

See:
hydromt build wflow test_5864 -r "{'subbasin': [123.970833333057,42.2791666666327], 'strord': 4,'bounds':[123.908333333333,42.0658333333333,124.9825,42.4583333333333]}" -i wflow_build_1km_vito_hydromt3.ini -d p:\wflow_global\hydromt\deltares_data.yml -vv

![image](https://github.com/Deltares/hydromt_wflow/assets/11685807/8abc1484-111c-43b9-b994-7c8a4bce7681)
![image](https://github.com/Deltares/hydromt_wflow/assets/11685807/9bb975ef-84ee-446c-bdac-00cb4fa194af)

### Current behaviour

reservoir ignored

### Desired behaviour

when option selected reservoir appears

**Comment by hboisgon** [comment]
Maybe try and solve together with #182

**Comment by atsiokanos** [comment]
Indeed this can be solved by changing the `predicate` (see config below) which is a bit hidden in `kwargs`. So I would say this is more of a documentation thing than a bug. Might be good to include it in the docs/method in a more explicit way.

```
  - setup_reservoirs_simple_control:
      reservoirs_fn: hydro_reservoirs  # source for reservoirs shape and attributes
      timeseries_fn: gww           # additional source for reservoir are timeseries to compute reservoirs, Either 'gww' using gwwapi or 'jrc' using hydroengine.
      min_area: 1           # minimum lake area to consider [km2]
      predicate: "intersects"
```
