### ISSUE TITLE
Config component

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt_wflow#342]
### Kind of request

We need to add the ConfigComponent to the WflowModel.

Also, the config component needs to be able to write groups of variables into one.

For example

```toml
[input.vertical]
khorfrac.value = 100
kverfrac.value = 200

# instead of 

[input.vertical.khorfrac]
value = 100

[input.vertical.kverfract]
value = 200
```

Also, there are values that contain a tilde (~) and they need to be quoted ("")

```toml
vegetation_canopy_water__mean_evaporation-to-mean_precipitation_ratio.value = 0.11
"soil~compacted_surface_water__infiltration_capacity".value = 5
soil_water_sat-zone_bottom__max_leakage_volume_flux.value = 0
"soil_root~wet__sigmoid_function_shape_parameter".value = -500
atmosphere_air__snowfall_temperature_threshold.value = 0
atmosphere_air__snowfall_temperature_interval.value = 2
 ```

- [ ] Add WflowConfigComponent
- [x] Customize the write functionality to support the cases defined above. See #79 
- [ ] Add new tests
- [ ] Merge to v1 branch

### Enhancement Description

For the move to hydromt-core v1 we should use a config component.
