### ISSUE TITLE
Resolve hardcoded `RESAMPLING` and `DTYPES` variables in landuse.py

### ISSUE THREAD

**Issue by LuukBlom** [Deltares/hydromt_wflow#430]
### Kind of request

None

### Enhancement Description

during renaming, this came up as an issue to be resolved. 

### Use case

When users provide custom names, the hardcoded stuff will break their models.

### Additional Context

https://github.com/Deltares/hydromt_wflow/pull/424/files#r2106973183

**Comment by deltamarnix** [comment]
@shartgring Would you be okay if we pin those names down and not have the option to have your own names? You example could then look like this:

```yaml
  - setup_lulcmaps:
      lulc_fn : lulc_mapbiomas
      lulc_mapping_fn: lulc_mapbiomas_mapping
      lulc_vars: 
       - land_manning_n
       - land_water_fraction
       - landuse
       - soil_compacted_fraction
       - vegetation_crop_factor
       - vegetation_kext
       - vegetation_leaf_storage
       - vegetation_root_depth
       - vegetation_wood_storage
 ```
