### ISSUE TITLE
Create Config File Converter for YAML

### ISSUE THREAD

**Issue by alimeshgi** [Deltares/hydromt_wflow#447]
To support migration and backward compatibility, we need a tool to convert older or alternative config formats into the current YAML structure used by HydroMT-wflow.

- [ ] Script/tool reads legacy config formats.
- [ ] Outputs valid YAML matching the current schema.
- [ ] Includes validation and error handling.
- [ ] Documented with examples.

**Comment by atsiokanos** [comment]
Hi, I think this is not really necessary and I do not see much added value. I wouldn’t spend time developing this. In most cases when building a wflow model the config remains the same with only minor adjustments to the settings.

Also with such a function you should convert the old ini config file (?). I don’t see any huge differences between the yml in older/current versions and v1. As a user I always go here [Building a model — HydroMT Wflow documentation](https://deltares.github.io/hydromt_wflow/stable/user_guide/wflow_build.html) I download the example config file and I manually modify it. Also in rc1 testing I created my own yml config to build/update the models based on this and didn’t think of updating the old config.

Actually even with this tool I would simply download the example rather than trying to use the converter function.

Regarding backward compatibility we could switch between different versions (similar to the tool in the top right corner of HydroMT core docs) in the example config.

**Comment by deltamarnix** [comment]
@atsiokanos the biggest difference is how the steps and global data is configured. You can see that the steps now require a `-` in front of every step. And there is some global data.



```yml
modeltype: wflow
global:
        data_libs: deltares_data
steps:
        - setup_basemaps:
                region: {'basin': [6.16, 51.84]}
                res: 0.008333
                hydrography_fn: merit_hydro
        - grid.add_data_from_geodataframe:
                vector_data: administrative_areas
                variables: "id_level1"
        - grid.add_data_from_geodataframe:
                vector_data: administrative_areas
                variables: "id_level3"
        - setup_reservoirs:
                reservoirs_fn: hydro_reservoirs
                min_area: 1.0
        - write:
                components:
                        - grid
                        - config
        - geoms.write:
                filename: geoms/*.gpkg
                driver: GPKG
```

The old one used to have only steps like so:

```yml
        setup_basemaps:
              region: {'basin': [6.16, 51.84]}
              res: 0.008333
              hydrography_fn: merit_hydro
        grid.add_data_from_geodataframe:
              vector_data: administrative_areas
              variables: "id_level1"
        grid.add_data_from_geodataframe:
              vector_data: administrative_areas
              variables: "id_level3"
        setup_reservoirs:
              reservoirs_fn: hydro_reservoirs
              min_area: 1.0
        write:
              components:
                      - grid
                      - config
        geoms.write:
              filename: geoms/*.gpkg
              driver: GPKG
```
