### ISSUE TITLE
Change lake and reservoir setup (1.0 rc)

### ISSUE THREAD

**Issue by vers-w** [Deltares/hydromt_wflow#459]
For the Wflow kernel (1.0 rc) we are restructuring the lake and reservoir structs (see also https://github.com/Deltares/Wflow.jl/issues/353 and https://github.com/Deltares/Wflow.jl/pull/634). Together with @JoostBuitink  and @hboisgon we have decided to use the term `reservoir` for both reservoirs and lakes.

Below an example of the TOML settings: 

```toml
[state.variables]
reservoir_water_surface__instantaneous_elevation = "waterlevel_reservoir"

[input]
reservoir_area__count = "wflow_reservoirareas"
reservoir_location__count = "wflow_reservoirlocs"

[input.static]
reservoir_surface__area = "reservoir_area"
"reservoir_water_demand~required~downstream__volume_flow_rate" = "ResDemand"
reservoir_water_release-below-spillway__max_volume_flow_rate = "ResMaxRelease"
reservoir_water__max_volume = "ResMaxVolume"
"reservoir_water~full-target__volume_fraction" = "ResTargetFullFrac"
"reservoir_water~min-target__volume_fraction" = "ResTargetMinFrac"
reservoir_water_surface__initial_elevation = "waterlevel_reservoir"
reservoir_water__rating_curve_type_count = "outflowfunc"
reservoir_water__storage_curve_type_count = "storfunc"
```

For the simple reservoir functionality also these variables need to be set: 
- `reservoir_water__rating_curve_type_count` (4)
- `reservoir_water__storage_curve_type_count` (1)
- `reservoir_water_surface__initial_elevation` (fullfrac * max_volume / area)
