### ISSUE TITLE
using setup_config_output_timeseries with WflowModel

### ISSUE THREAD

**Issue by shartgring** [Deltares/hydromt_wflow#464]
### HydroMT-Wflow version checks

- [x] I have checked that this issue has not already been reported.
- [x] I have checked that this bug exists on the latest version of HydroMT-Wflow.

### Reproducible Example

Using `setup_config_output_timeseries` results in a toml that is not valid

### Current behaviour

Using the method yields
```
output.csv.path = "output.csv"
output.csv.column = [{header = "Q",map = "gauges_obs",parameter = "lateral.river.q_av"}]
```
in the toml. In this case, there was no `output` header present which may cause the problem.

### Desired behaviour

This could either be something to be fixed, or the method should include a check if the header exists and otherwise raise an error or not add anything at all to the toml

**Comment by atsiokanos** [comment]
Hey @shartgring I worked with this method quite a lot in the past in a wflow build yml config and worked fine. Below an example:

``````
setup_config_output_timeseries2:
  mapname: "wflow_subcatch"
  header:
    - "precip_subcatch"
    - "pet_subcatch"
    - "etact_subcatch"
    - "snow_subcatch"
    - "rainfallplusmelt_subcatch"
    - "temp_subcatch"
  param:
    - "vertical.precipitation"
    - "vertical.potential_evaporation"
    - "vertical.actevap"
    - "vertical.snow"
    - "vertical.rainfallplusmelt"
    - "vertical.temperature"
  reducer:
    - "mean"
    - "mean"
    - "mean"
    - "mean"
    - "mean"
    - "mean"
  ``````

**Comment by Tjalling-dejong** [comment]
I could not replicate your issue. Can you share a reproducible example?
Also note that the example toml entries you gave are valid toml entries. It just looks different from the initial toml file.

**Comment by shartgring** [comment]
You're right! I was not aware that this was valid as I did not recognize it from the Wflow docs https://deltares.github.io/Wflow.jl/dev/user_guide/toml_file.html#output-csv-section. I tested it and indeed the Wflow models are running

Still, it might be a good question to check if the formatting is something that we want, as for now using:
```
model = WflowModel(root=...)
model.setup_config_output_timeseries(mapname="test", toml_output="csv", header=["Q"], param=["lateral.river.q_av"])
model.setup_config_output_timeseries(mapname="testtest", toml_output="csv", header=["Q"], param=["lateral.river.q_av"])
model.write_config()
```
yields:
```
dir_output = "run_default"
output.csv.path = "output.csv"
output.csv.column = [{header = "Q",map = "test",parameter = "lateral.river.q_av"}, {header = "Q",map = "testtest",parameter = "lateral.river.q_av"}]
```

**Comment by Tjalling-dejong** [comment]
Thanks for the example @shartgring. I just ran your code and I get the correct formatting. Could you update your environment and try again?

**Comment by LuukBlom** [comment]
linked to TOMLkit version, now resolved in v0.13.3

**Comment by deltamarnix** [comment]
@shartgring I was able to reproduce your issue in a different way and it really has to do with removing items from the default config as we supply it. I don't see a need to remove `output.csv` if you are going to add items to it.

This is the test that I wrote:
```py
def test_setup_config_output_config_without_output_csv(tmpdir):
    model = WflowModel(root=tmpdir)
    model.remove_config("output", "csv")
    model.setup_config_output_timeseries(
        mapname="test", toml_output="csv", header=["Q"], param=["lateral.river.q_av"]
    )
    model.write_config()
    with open(join(tmpdir, "wflow_sbm.toml"), "r") as f:
        content = f.read()
        assert "[[output.csv.column]]" in content
```

And the output is the following:

```toml
...
[input.static]

csv.path = "output.csv"
[[csv.column]]
header = "Q"
map = "test"
parameter = "lateral.river.q_av"

[output.netcdf_grid]

[output.netcdf_grid.variables]

[output.netcdf_scalar]
```

I agree it is wrong, because now it actually says `input.static.csv.path = "output.csv"`.
The toml is valid, although it is not what we had specified.

I am able to get the correct output by not removing `output.csv` from the config:

```py
def test_setup_config_output_config_without_output_csv(tmpdir):
    model = WflowModel(root=tmpdir)
#    model.remove_config("output", "csv")
    model.setup_config_output_timeseries(
        mapname="test", toml_output="csv", header=["Q"], param=["lateral.river.q_av"]
    )
    model.write_config()
    with open(join(tmpdir, "wflow_sbm.toml"), "r") as f:
        content = f.read()
        assert "[[output.csv.column]]" in content
```

```toml
[input.static]

[output.netcdf_grid]

[output.netcdf_grid.variables]

[output.csv]
path = "output.csv"

[[output.csv.column]]
header = "Q"
map = "test"
parameter = "lateral.river.q_av"
[output.netcdf_scalar]
```

I am closing this issue for now. Please do not remove items in the config that you are going to add back afterwards. I agree it is wrong and I will create an issue in tomlkit.
